### PR TITLE
[Swift+WASM] Adopt SwiftABIInfo for WebAssembly.

### PR DESCRIPTION
**Pull request by ddunbar**

### CODE REVIEW

**Comment by ddunbar** [comment]
This is part of super early days exploration of what is required for WASM support. Given the open-ended nature of it, and the instability of WASM itself and the LLVM implementation, I haven't really tried to make this a very principled implementation but rather am trying to work through the minimal changes needed to start getting end-to-end `wasm` objects out of Swift.

LMK if you think this is a reasonable approach & way to land...

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
This approach seems reasonable to me. I expect there will be a lot of experimentation needed to figure out how best to do this

**Comment by ddunbar** [comment]
@DougGregor do we have smoke testing for Clang changes? Is merging into `stable` the right thing to do?

**Comment by ddunbar** [comment]
Hmm from looking at other PRs I guess I’m supposed to go to upstream-with-swift maybe?

**Comment by ddunbar** [comment]
Switch to be a PR against `upstream-with-swift`

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test linux platform

**Comment by ddunbar** [comment]
@swift-ci please test MacOSX platform

**Comment by ddunbar** [comment]
Closing this, this code has been upstreamed to Clang (https://github.com/llvm-mirror/clang/commit/c72bf467c95d38f437f2dbacddf38611c21aa99a)

**Pull request closed without merging**
