### PR TITLE
Add missing newline at end of file

### PR DESCRIPTION
**Pull request by jtbandes**
I see warnings in Xcode about this file when building Swift.

### CODE REVIEW

**Comment by DougGregor** [comment]
Has this been fixed upstream yet?

Also, it should go into swift-3_1-branch, then it'll get merged into stable.

**Comment by hyp** [comment]
This was already fixed in r285428 upstream.

**Comment by hyp** [comment]
I will cherry-pick the fix from r285428 to swift-3.1-branch on monday

**Comment by hyp** [comment]
I cherry-picked r285428 to 7c56a6a3dc64662f9aab1e80ec5308f3c50a8c8e. I'm closing this now as this issue is fixed.

**Comment by jtbandes** [comment]
Thanks!

**Pull request closed without merging**
