### PR TITLE
Fix Linux build of DirectoryWatcher

### PR DESCRIPTION
**Pull request by benlangmuir**
Use the correct namespace.

rdar://48452986

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@jkorous-apple I don't know why this code built in upstream, so I'll leave it to you to figure out what needs to be done on llvm.org, if anything.  It looks like you didn't put your original attempt to fix this in any branches other than 5.1, so I did the same.  Is that really what we want? Won't that mean the fix disappears in the future?

**Comment by benlangmuir** [comment]
Wasn't enough:

<details>
<summary>error: no matching function for call to 'RetryAfterSignal'</summary>

```
In file included from /home/buildnode/jenkins/workspace/swift-clang-PR-Linux/llvm/tools/clang/lib/DirectoryWatcher/DirectoryWatcher.cpp:98:
/home/buildnode/jenkins/workspace/swift-clang-PR-Linux/llvm/tools/clang/lib/DirectoryWatcher/DirectoryWatcher-linux.inc.h:95:23: error: no matching function for call to 'RetryAfterSignal'
    ssize_t numRead = llvm::sys::RetryAfterSignal(-1, read, inotifyFD, buf, EventBufferLength);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/buildnode/jenkins/workspace/swift-clang-PR-Linux/llvm/include/llvm/Support/Errno.h:34:13: note: candidate template ignored: substitution failure [with FailT = int, Fun = long (int, void *, unsigned long), Args = <int, char [8160], unsigned long>]: cannot initialize a parameter of type 'void *' with an lvalue of type 'char const[8160]'
inline auto RetryAfterSignal(const FailT &Fail, const Fun &F,
            ^
In file included from /home/buildnode/jenkins/workspace/swift-clang-PR-Linux/llvm/tools/clang/lib/DirectoryWatcher/DirectoryWatcher.cpp:98:
/home/buildnode/jenkins/workspace/swift-clang-PR-Linux/llvm/tools/clang/lib/DirectoryWatcher/DirectoryWatcher-linux.inc.h:100:36: error: 'char' is not a class
      struct inotify_event *ievt = dynamic_cast<struct inotify_event *>(p);
                                   ^                                    ~
2 errors generated.
```
</details>

**Comment by compnerd** [comment]
@benlangmuir - its a C++ feature!  Need a `reinterpret_cast<void *>(buf)` on the fourth formal argument.

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Ugh, I just saw the second error about dynamic_cast.  This code has clearly never been compiled or tested.  We should just revert it all.

**Comment by benlangmuir** [comment]
Closing in favour of https://github.com/apple/swift-clang/pull/265

**Pull request closed without merging**
