### PR TITLE
Fix autotools build

### PR DESCRIPTION
**Pull request by jroelofs**

### CODE REVIEW

**Comment by jrose-apple** [comment]
The autotools build of LLVM/Clang isn't supported in any Swift branches (and has been removed from upstream LLVM).

**Comment by jroelofs** [comment]
Ah, I didn't catch that. Are there plans to merge cbeineman's
upstream patch to remove the autotools build to this branch?

Jon

**Comment by jrose-apple** [comment]
No, it's just that it's languished and never been tested with Swift. At this point the 2.2 Clang branch is pretty much frozen, but we should probably at least merge Chris's commit to the 3.0 branch, now that you mention it.

**Comment by gribozavr** [comment]
We will merge it as a part of the stable merge later.

**Pull request closed without merging**
