### PR TITLE
Remove -cc1apinotes entry point and stop looking for apinotesc files

### PR DESCRIPTION
**Pull request by jrose-apple**
First half of removing "compiled" API notes. The second half is not bothering to bounce through the binary format in memory.

### CODE REVIEW

**Comment by jrose-apple** [comment]
Let's see if testing works these days. I see that the bot is currently failing, but I can see if it makes things worse…

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
:-/ Too many unrelated errors to really get a signal.

**Review by DougGregor — APPROVED** [review]
So many beautiful, beautiful `-`'s

**Pull request merged**
