### PR TITLE
[APINotes] Add support for distinguishing class vs. instance properties.

### PR DESCRIPTION
**Pull request by DougGregor**

### CODE REVIEW

**Comment by DougGregor** [comment]
Please test with following pull request:
https://github.com/apple/swift-llvm/pull/25

@swift-ci Please test

**Comment by DougGregor** [comment]
@shahmishal , failing due to missing tag in the playground repo:

Branch swift-3.1-branch set up to track remote branch swift-3.1-branch from origin.
- git clone --recursive https://github.com/apple/swift-xcode-playground-support.git swift-xcode-playground-support
  Cloning into 'swift-xcode-playground-support'...
  error: pathspec 'swift-3.1-branch' did not match any file(s) known to git.
  Found related pull requests: ['apple/swift-llvm/pull/25']

**Comment by jrose-apple** [comment]
Yeah, this branch doesn't exist in most repos yet—only the LLVM projects have branched (LLDB may or may not have).

**Comment by shahmishal** [comment]
@DougGregor This is failing because we need to update the checkout script to support swift-3.1-branch.

**Pull request merged**
