### PR TITLE
Disable using `-fsanitize=leak` from the Clang Driver.

### PR DESCRIPTION
**Pull request by ghost**
LeakSanitizer (LSan) is not yet mature for Darwin so until this
changes we should avoid supporting it in Swift Clang and AppleClang.

rdar://problem/45841334

### CODE REVIEW

**Review by kubamracek — APPROVED** [review]

**Review by hyp — APPROVED** [review]

**Review by jrose-apple — DISMISSED** [review]
This branch is used to build for Linux too. I think we even run Leak Sanitizer on Swift stuff there.

**Comment by jrose-apple** [comment]
In general, `upstream-with-swift` should not have anything in it that isn't specific to Swift. Other Apple-specific stuff should stay Apple-internal at this time.

**Comment by danliew-apple** [comment]
@jrose-apple This change is only for Darwin. Linux should remain unchanged by this PR.

**Comment by danliew-apple** [comment]
@jrose-apple 
> In general, upstream-with-swift should not have anything in it that isn't specific to Swift. Other Apple-specific stuff should stay Apple-internal at this time.

This patch was originally intended to be internal but @hyp requested it be moved here.

**Comment by delcypher** [comment]
@jrose-apple The commits shouldn't mention `Apple-internal` anymore. So I'll land this.

**Pull request merged**
