### PR TITLE
ppc64le port.

### PR DESCRIPTION
**Pull request by asowani**
As mentioned in https://github.com/apple/swift-clang/pull/160 I am merging ppc64le changes to "upstream-with-swift" branch first. Please review.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
Does the PPC backend support swifterror?

A quick check seems to indicate that it does not:

```
$ git show origin/upstream-with-swift:lib/Target/PowerPC/PPCCallingConv.td | grep Swift
```

If it does not support swifterror it is more likely that  

```
bool isSwiftErrorInRegister() const override {    
  return false;
}
```
will work correctly.

**Comment by asowani** [comment]
@aschwaighofer Thanks for reviewing code changes, I have done required modifications and have committed again.

**Review by aschwaighofer — APPROVED** [review]
Looks good to me.

**Comment by asowani** [comment]
Hi! Any idea when this PR will be merged? Thanks!

**Comment by bob-wilson** [comment]
We should have mentioned this sooner, but ideally this change should be applied to the llvm.org version of Clang. We really should have this version get out of sync with trunk more than it already is. But, since no one told you that until now, I don't want to block your progress. As a compromise, if we merge this now, can you add this change on reviews.llvm.org?

**Comment by asowani** [comment]
@bob-wilson Sure, I will initiate process to add these changes to llvm.org right away. Thanks!

**Comment by bob-wilson** [comment]
OK. I went ahead and merged this then.

**Comment by bob-wilson** [comment]
I pulled the change over to swift-4.2-branch (https://github.com/apple/swift-clang/pull/171) and it will be automatically merged from there into stable.

**Comment by asowani** [comment]
@bob-wilson Thanks! I have started upstreaming changes to llvm.

**Comment by bob-wilson** [comment]
I haven't seen a patch sent to Clang at llvm.org yet. Can you please do that soon?

**Comment by asowani** [comment]
Hi Bob,
 
I apologize for the delay in upstreaming the patch. I have kept everything ready and am just waiting for formal approval from my employer to contribute to LLVM repositories. I have already secured this approval from Apple Swift repositories. I am actively pursuing this and hopefully I will be able to upstream the code by this or early next week. I am really sorry for the delay and thank you for your patience so far.
 
Thanks and best regards,
Atul.
 
----- Original message -----From: Bob Wilson <notifications@github.com>To: apple/swift-clang <swift-clang@noreply.github.com>Cc: Atul Sowani <sowania@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [apple/swift-clang] ppc64le port. (#167)Date: Tue, Apr 17, 2018 10:27 PM 
I haven't seen a patch sent to Clang at llvm.org yet. Can you please do that soon?

**Comment by asowani** [comment]
@bob-wilson I got clearance from my employer to upstream code changes to LLVM. I've filed a new bug for this in LLVM bugzilla: https://bugs.llvm.org/show_bug.cgi?id=37223

**Comment by asowani** [comment]
@bob-wilson I have uploaded the patch to the bug which I created yesterday. (https://bugs.llvm.org/show_bug.cgi?id=37223)

**Pull request merged**
