### PR TITLE
[tools] Add private to link_target_libraries.

### PR DESCRIPTION
**Pull request by dcci**
This unbreaks swift-lldb testing.

### CODE REVIEW

**Comment by dcci** [comment]
Sorry, this should be phrased as: this unbreaks the `upstream-with-swift` branch of `swift-clang`, which is the first step needed to unbreak lldb `upstream-with-swift` branch

**Comment by dcci** [comment]
@swift-ci please test

**Comment by fredriss** [comment]
The change looks pretty safe, I just merged it

**Comment by dcci** [comment]
Thanks @fredriss !

**Pull request merged**
