### PR TITLE
Basic: adjust for overflow in diagnostics

### PR DESCRIPTION
**Pull request by compnerd**
Recent upstream changes has caused the number of diagnostics to overflow.
Increase the count.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bob-wilson @dexonsmith @gottesmm

**Comment by gottesmm** [comment]
@jrose-apple would be good to look at this. On a more meta level, why only increase by 3? Why not bump it by 100 or something?

**Comment by compnerd** [comment]
@gottesmm - thats what the current need is which is why.  I'm not tied to 3 :-)

**Comment by compnerd** [comment]
CC: @atrick

**Comment by bob-wilson** [comment]
Bumping it by 3 (or however many more diagnostics we have in swift-clang) seems OK to me. The limit on trunk will get bumped soon, and presumably that will go up by a significant amount. E.G., if the trunk limit goes from 3500 to 3600, the swift-clang version can go from 3503 to 3603 (or even just leave it at 3600 and repeat this process when/if we get close to that limit).

**Comment by gottesmm** [comment]
@bob-wilson I agree it is reasonable. +1 from me.

**Pull request merged**
