### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
@tkremenek - these fixes are needed to build clang on Windows (they already are on upstream-with-swift, this cherry-picks them into stable).

**Comment by compnerd** [comment]
This should be going into swift-4.2-branch.  CC: @bob-wilson

**Comment by compnerd** [comment]
Ugh, need to rebase it.

**Comment by tkremenek** [comment]
@compnerd keep in mind `swift-4.2-branch` will also rebranch from `master` again on April 20 (for the last time).

**Comment by bob-wilson** [comment]
Looks good to me.
@tkremenek : this is for the swift-clang repo so we're not rebranching it again for 4.2.

hmm... I was replying to a comment from Ted that seems to have disappeared so I guess he already realized that.

**Comment by tkremenek** [comment]
Yeah I realized it and deleted my comment.

**Pull request merged**
