### PR TITLE
Directory watcher

### PR DESCRIPTION
**Pull request by jkorous-apple**

### CODE REVIEW

**Comment by bob-wilson** [comment]
Isn't this the same as https://github.com/apple/swift-clang/pull/265?

**Comment by jkorous-apple** [comment]
No, I'm actually trying to fix this. Those are reverts of Ben's reverts + fixes (still one missing).

**Comment by jkorous-apple** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by jkorous-apple** [comment]
@swift-ci please test

**Comment by jkorous-apple** [comment]
@swift-ci please test

**Pull request closed without merging**
