### PR TITLE
[CrashReproducer] Upstream a test for -index-store-path support.

### PR DESCRIPTION
**Pull request by vsapsai**
Patch by Bruno Cardoso Lopes.

### CODE REVIEW

**Comment by vsapsai** [comment]
@swift-ci Please test

**Comment by bcardosolopes** [comment]
When the tests pass (assuming failures are related), LGTM

**Comment by vsapsai** [comment]
Testing failure seems to be unrelated to the change
> /Users/buildnode/jenkins/workspace/swift-clang-PR-osx/swift/stdlib/public/Darwin/Foundation/Data.swift:563:24: error: property does not override any property from its superclass

Will restart PR testing.

**Comment by vsapsai** [comment]
@swift-ci Please test

**Comment by vsapsai** [comment]
Rebased on top of the latest `upstream-with-swift`, let's test again.

@swift-ci Please test

**Comment by vsapsai** [comment]
Rebased past the broken `IndexingAction.cpp`, works locally on macOS.

@swift-ci Please test

**Review by bcardosolopes — APPROVED** [review]
LGTM

**Pull request merged**
