### PR TITLE
Revert "Use EmitPointerWithAlignment to get alignment information of …

### PR DESCRIPTION
**Pull request by gottesmm**
…the pointer used in atomic expr."

This reverts commit c3ee9f507de5523bcc473c6724f1d3da7702699e.

It broke libdispatch.

<rdar://problem/34944963>

### CODE REVIEW

**Comment by gottesmm** [comment]
This is just a test to see if this fixes the Swift build.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Passes the Linux build. Merging!

**Comment by vedantk** [comment]
Thanks for the revert. I'll take a closer look at what happened.

**Comment by vedantk** [comment]
@gottesmm apologies, I did not see that this was reverted in r312830. I should have cherry-picked r314145, but given this failure I'd rather not take the risk for the 4.1 branch.

**Comment by gottesmm** [comment]
Just test it on swift-clang PR machinery before committing = ).

**Comment by gottesmm** [comment]
@vedantk Then you will never have to worry about this = p.

**Comment by vedantk** [comment]
I'll do that for my next batch of cherry picks.

**Pull request merged**
