### PR TITLE
Fix Windows support for Driver and add support to Index

### PR DESCRIPTION
**Pull request by troughton**
This pull request contains fixes to enable Clang to build on Windows against the MSVC toolchain.

Of particular note is the change from timespec to time_t in IndexDataStore.h; this field doesn't seem to be in use, and time_t is consistent with elsewhere in the repository, but the two types are not equivalent, so I'm not certain this change is correct.

https://github.com/apple/swift-clang/pull/113 rebased off upstream-with-swift

### CODE REVIEW

**Comment by akyrtzi** [comment]
It *is* getting used, see function indexstore_unit_event_get_modification_time, part of the libIndexStore C library. That function should not change, it would break the ABI.
Also it originates from `DirectoryWatcher.cpp`, I'm not sure why you didn't have to touch that or the C library.

`timespec` is supposed to be part of `time.h`, does the Windows headers really not provide it ?

**Comment by troughton** [comment]
`timespec` isn't included on Windows; a quick web search reveals a number of different suggestions for replacement that all differ slightly in functionality.

I missed DirectoryWatcher.cpp because I (mistakenly) only tested on Windows, where that code is hidden behind a `HAVE_CORESERVICES` define, so the type wasn't actually getting used.

Maybe a better solution would be just to declare the `timespec` struct on Windows; there's nothing in it that's inherently incompatible. If I were to do that, where would be the best place to declare it – in that same header file?

**Comment by akyrtzi** [comment]
We could replace it in the C++ code with llvm's TimePoint (from `llvm/Support/Chrono.h`), `getLastModificationTime()` uses that and DirectoryWatcher converts from it, but it could just pass it directly.
Then keep timespec in the C library and convert from TimePoint with the same way as DirectoryWatcher does it.

**Comment by troughton** [comment]
@akyrtzi Were you thinking something along the lines of these changes?

**Comment by akyrtzi** [comment]
You can also remove the `toTimeSpec()` function from `DirectoryWatcher.cpp`.
Also you can use `SafelyCloseFileDescriptor()` from `llvm/Support/Process.h` and avoid the platform-specific code in `IndexUnitReader.cpp`.

Otherwise LGTM.

**Comment by troughton** [comment]
Done, thanks.

**Comment by akyrtzi** [comment]
Is this part
```
+#if defined(_WIN32)
+#include <io.h>
+#else 
```
in `IndexUnitReader.cpp` still necessary ?

**Comment by troughton** [comment]
No, it's not; I got rid of it, and I also removed the `unistd.h` include since that's also now unnecessary.

**Review by akyrtzi — APPROVED** [review]

**Comment by troughton** [comment]
Just checking in - are we okay to merge this now?

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
master-next branch has issues, but I tested the changes on swift-4.1 and they look good, merging.

**Pull request merged**
